project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Portfolio"
  description: "Course Projects for STA 9750 (Basic Software Tools for Data Analysis) at Baruch College"
  site-url: "https://bklin12.github.io/STA9750-2026-FALL/"
  navbar:
    background: primary
    search: false
    left:
      - href: mp01.qmd
        text: Mini-Project 1
      - href: mp02.qmd
        text: Mini-Project 2
      - href: mp03.qmd
        text: Mini-Project 3
      - href: mp04.qmd
        text: Mini-Project 4

format:
  html:
    theme: flatly
    toc: false

editor:
  mode: source